export type ProjectState =
  "Avance normal" | "Riesgo moderado" | "Retraso" | "Crítico" | "En ejecución" | "No iniciado";

export type ProjectRisk = "Bajo" | "Moderado" | "Alto" | "Crítico";

export type GeographicProject = {
  id: string;
  code: string;
  name: string;
  type: string;
  department: string;
  province: string;
  tramo: string;
  sector: string;
  state: ProjectState;
  predialState: string;
  risk: ProjectRisk;
  responsible: string;
  longitude: number;
  latitude: number;
  investment: number;
  executed: number;
  physical: number;
  physicalTarget: number;
  properties: number;
  paid: number;
  delivered: number;
  registered: number;
  critical: number;
  areaRequired: number;
  areaDelivered: number;
  availabilityDate: string;
};

export const geographicProjects: GeographicProject[] = [
  {
    id: "jauja",
    code: "PRY-016",
    name: "Mejoramiento del Aeropuerto de Jauja",
    type: "Aeropuerto",
    department: "Junín",
    province: "Jauja",
    tramo: "Área aeroportuaria",
    sector: "Lado aire",
    state: "En ejecución",
    predialState: "Adquisición en proceso",
    risk: "Moderado",
    responsible: "Marcos Soto Luis",
    longitude: -75.473,
    latitude: -11.783,
    investment: 468_000_000,
    executed: 271_440_000,
    physical: 61,
    physicalTarget: 66,
    properties: 477,
    paid: 310,
    delivered: 240,
    registered: 200,
    critical: 12,
    areaRequired: 1_106_238,
    areaDelivered: 671_420,
    availabilityDate: "30/06/2027",
  },
  {
    id: "piura",
    code: "PRY-021",
    name: "Corredor Vial Piura – Sullana",
    type: "Corredor vial",
    department: "Piura",
    province: "Piura",
    tramo: "Piura – Sullana",
    sector: "Norte",
    state: "Riesgo moderado",
    predialState: "Tasación",
    risk: "Moderado",
    responsible: "Rafael Palomino Rojas",
    longitude: -80.632,
    latitude: -5.195,
    investment: 1_240_000_000,
    executed: 620_000_000,
    physical: 48,
    physicalTarget: 56,
    properties: 326,
    paid: 182,
    delivered: 145,
    registered: 98,
    critical: 18,
    areaRequired: 842_000,
    areaDelivered: 439_000,
    availabilityDate: "31/12/2027",
  },
  {
    id: "chancay",
    code: "PRY-028",
    name: "Acceso Vial al Terminal Portuario de Chancay",
    type: "Puerto",
    department: "Lima",
    province: "Huaral",
    tramo: "Acceso portuario",
    sector: "Chancay",
    state: "Avance normal",
    predialState: "Entrega física",
    risk: "Bajo",
    responsible: "Rosa Huamán Torres",
    longitude: -77.267,
    latitude: -11.571,
    investment: 780_000_000,
    executed: 585_000_000,
    physical: 78,
    physicalTarget: 76,
    properties: 168,
    paid: 142,
    delivered: 131,
    registered: 104,
    critical: 3,
    areaRequired: 384_000,
    areaDelivered: 319_000,
    availabilityDate: "30/11/2026",
  },
  {
    id: "huancayo-huancavelica",
    code: "PRY-033",
    name: "Ferrocarril Huancayo – Huancavelica",
    type: "Ferrocarril",
    department: "Huancavelica",
    province: "Huancavelica",
    tramo: "Tramo ferroviario integral",
    sector: "Centro",
    state: "Retraso",
    predialState: "Expediente técnico-legal",
    risk: "Alto",
    responsible: "Lucía Castro Díaz",
    longitude: -74.972,
    latitude: -12.786,
    investment: 1_890_000_000,
    executed: 642_600_000,
    physical: 31,
    physicalTarget: 45,
    properties: 512,
    paid: 214,
    delivered: 164,
    registered: 92,
    critical: 37,
    areaRequired: 1_344_000,
    areaDelivered: 465_000,
    availabilityDate: "30/09/2028",
  },
  {
    id: "iquitos",
    code: "PRY-041",
    name: "Terminal Portuario de Iquitos",
    type: "Terminal",
    department: "Loreto",
    province: "Maynas",
    tramo: "Área terminal",
    sector: "Ribera",
    state: "Crítico",
    predialState: "Conflicto",
    risk: "Crítico",
    responsible: "Miguel Rojas Silva",
    longitude: -73.247,
    latitude: -3.743,
    investment: 650_000_000,
    executed: 156_000_000,
    physical: 22,
    physicalTarget: 42,
    properties: 204,
    paid: 74,
    delivered: 42,
    registered: 25,
    critical: 29,
    areaRequired: 426_000,
    areaDelivered: 104_000,
    availabilityDate: "31/12/2028",
  },
  {
    id: "cusco",
    code: "PRY-047",
    name: "Vía de Evitamiento Cusco",
    type: "Carretera",
    department: "Cusco",
    province: "Cusco",
    tramo: "Evitamiento urbano",
    sector: "Este",
    state: "En ejecución",
    predialState: "Negociación",
    risk: "Moderado",
    responsible: "Carlos Mendoza Peña",
    longitude: -71.967,
    latitude: -13.522,
    investment: 925_000_000,
    executed: 508_750_000,
    physical: 57,
    physicalTarget: 61,
    properties: 288,
    paid: 173,
    delivered: 139,
    registered: 86,
    critical: 11,
    areaRequired: 765_000,
    areaDelivered: 422_000,
    availabilityDate: "31/08/2027",
  },
  {
    id: "arequipa",
    code: "PRY-052",
    name: "Puente Metropolitano Arequipa",
    type: "Puente",
    department: "Arequipa",
    province: "Arequipa",
    tramo: "Cruce metropolitano",
    sector: "Cerro Colorado",
    state: "Avance normal",
    predialState: "Pago",
    risk: "Bajo",
    responsible: "Ana Paredes Vega",
    longitude: -71.537,
    latitude: -16.398,
    investment: 430_000_000,
    executed: 318_200_000,
    physical: 76,
    physicalTarget: 74,
    properties: 96,
    paid: 81,
    delivered: 72,
    registered: 58,
    critical: 2,
    areaRequired: 158_000,
    areaDelivered: 124_000,
    availabilityDate: "31/10/2026",
  },
  {
    id: "pucallpa",
    code: "PRY-059",
    name: "Sistema de Saneamiento Pucallpa",
    type: "Saneamiento",
    department: "Ucayali",
    province: "Coronel Portillo",
    tramo: "Red principal",
    sector: "Yarinacocha",
    state: "Riesgo moderado",
    predialState: "Empadronamiento",
    risk: "Moderado",
    responsible: "Patricia Núñez Soto",
    longitude: -74.553,
    latitude: -8.379,
    investment: 710_000_000,
    executed: 291_100_000,
    physical: 43,
    physicalTarget: 50,
    properties: 234,
    paid: 101,
    delivered: 78,
    registered: 44,
    critical: 14,
    areaRequired: 512_000,
    areaDelivered: 211_000,
    availabilityDate: "30/06/2028",
  },
  {
    id: "tacna",
    code: "PRY-064",
    name: "Terminal Terrestre Intermodal de Tacna",
    type: "Proyecto multimodal",
    department: "Tacna",
    province: "Tacna",
    tramo: "Área intermodal",
    sector: "Gregorio Albarracín",
    state: "No iniciado",
    predialState: "Identificación",
    risk: "Alto",
    responsible: "Fernando Valdivia Cruz",
    longitude: -70.251,
    latitude: -18.014,
    investment: 540_000_000,
    executed: 32_400_000,
    physical: 6,
    physicalTarget: 14,
    properties: 142,
    paid: 21,
    delivered: 9,
    registered: 4,
    critical: 17,
    areaRequired: 298_000,
    areaDelivered: 22_000,
    availabilityDate: "31/12/2029",
  },
];

export const projectStateColors: Record<ProjectState, string> = {
  "Avance normal": "#16a34a",
  "Riesgo moderado": "#eab308",
  Retraso: "#f97316",
  Crítico: "#dc2626",
  "En ejecución": "#2563eb",
  "No iniciado": "#6b7280",
};
