export type Proyecto = {
  id: string;
  codigo: string;
  nombre: string;
  tipo: string;
  coordinacionGeneral: string;
  coordinacionPredial: string;
  coordinadorPredial: string;
  liderInterferencias: string;
  img: string;
  fase: string;
  estado: "En estructuracion" | "En ejecucion" | "En revision";
  presupuesto: string;
  fisico: number;
  financiero: number;
  predios: number;
  disponibles: number;
};

const projectSeed: Proyecto[] = [
  {"id": "iquitos", "codigo": "PRY-001", "nombre": "Iquitos", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=800&q=70&auto=format&fit=crop", "fase": "Levantamiento topografico", "estado": "En ejecucion", "presupuesto": "S/ 44.3 MM", "fisico": 29, "financiero": 30, "predios": 64, "disponibles": 28},
  {"id": "trujillo", "codigo": "PRY-002", "nombre": "Trujillo", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800&q=70&auto=format&fit=crop", "fase": "Saneamiento fisico legal", "estado": "En revision", "presupuesto": "S/ 100.0 MM", "fisico": 22, "financiero": 28, "predios": 69, "disponibles": 242},
  {"id": "chachapoyas", "codigo": "PRY-003", "nombre": "Chachapoyas", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1583500178690-f7eb3c2dd6cc?w=800&q=70&auto=format&fit=crop", "fase": "Liberacion predial", "estado": "En estructuracion", "presupuesto": "S/ 64.8 MM", "fisico": 14, "financiero": 10, "predios": 262, "disponibles": 117},
  {"id": "chiclayo", "codigo": "PRY-004", "nombre": "Chiclayo", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800&q=70&auto=format&fit=crop", "fase": "Disponibilidad de areas", "estado": "En ejecucion", "presupuesto": "S/ 15.8 MM", "fisico": 21, "financiero": 40, "predios": 257, "disponibles": 25},
  {"id": "tumbes", "codigo": "PRY-005", "nombre": "Tumbes", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=70&auto=format&fit=crop", "fase": "Diagnostico predial", "estado": "En revision", "presupuesto": "S/ 100.6 MM", "fisico": 25, "financiero": 65, "predios": 154, "disponibles": 171},
  {"id": "pucallpa", "codigo": "PRY-006", "nombre": "Pucallpa", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=800&q=70&auto=format&fit=crop", "fase": "Levantamiento topografico", "estado": "En estructuracion", "presupuesto": "S/ 78.3 MM", "fisico": 17, "financiero": 41, "predios": 243, "disponibles": 22},
  {"id": "anta-huaraz", "codigo": "PRY-007", "nombre": "Anta-HUARAZ", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800&q=70&auto=format&fit=crop", "fase": "Saneamiento fisico legal", "estado": "En ejecucion", "presupuesto": "S/ 117.3 MM", "fisico": 15, "financiero": 40, "predios": 108, "disponibles": 84},
  {"id": "pisco", "codigo": "PRY-008", "nombre": "Pisco", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1583500178690-f7eb3c2dd6cc?w=800&q=70&auto=format&fit=crop", "fase": "Liberacion predial", "estado": "En revision", "presupuesto": "S/ 54.9 MM", "fisico": 25, "financiero": 41, "predios": 197, "disponibles": 153},
  {"id": "tarapoto", "codigo": "PRY-009", "nombre": "Tarapoto", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800&q=70&auto=format&fit=crop", "fase": "Disponibilidad de areas", "estado": "En estructuracion", "presupuesto": "S/ 99.4 MM", "fisico": 33, "financiero": 11, "predios": 136, "disponibles": 105},
  {"id": "cajamarca", "codigo": "PRY-010", "nombre": "Cajamarca", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=70&auto=format&fit=crop", "fase": "Diagnostico predial", "estado": "En ejecucion", "presupuesto": "S/ 18.9 MM", "fisico": 18, "financiero": 41, "predios": 70, "disponibles": 168},
  {"id": "talara", "codigo": "PRY-011", "nombre": "Talara", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=800&q=70&auto=format&fit=crop", "fase": "Levantamiento topografico", "estado": "En revision", "presupuesto": "S/ 31.1 MM", "fisico": 64, "financiero": 54, "predios": 200, "disponibles": 129},
  {"id": "piura", "codigo": "PRY-012", "nombre": "Piura", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 01", "coordinadorPredial": "Gilbert Manuel Aguirre Gómez", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800&q=70&auto=format&fit=crop", "fase": "Saneamiento fisico legal", "estado": "En estructuracion", "presupuesto": "S/ 73.6 MM", "fisico": 68, "financiero": 28, "predios": 193, "disponibles": 73},
  {"id": "andahuaylas", "codigo": "PRY-013", "nombre": "Andahuaylas", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 02", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1583500178690-f7eb3c2dd6cc?w=800&q=70&auto=format&fit=crop", "fase": "Liberacion predial", "estado": "En ejecucion", "presupuesto": "S/ 97.0 MM", "fisico": 41, "financiero": 10, "predios": 193, "disponibles": 144},
  {"id": "ayacucho", "codigo": "PRY-014", "nombre": "Ayacucho", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 02", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800&q=70&auto=format&fit=crop", "fase": "Disponibilidad de areas", "estado": "En revision", "presupuesto": "S/ 63.5 MM", "fisico": 53, "financiero": 51, "predios": 269, "disponibles": 83},
  {"id": "juliaca", "codigo": "PRY-015", "nombre": "Juliaca", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 02", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=70&auto=format&fit=crop", "fase": "Diagnostico predial", "estado": "En estructuracion", "presupuesto": "S/ 76.2 MM", "fisico": 19, "financiero": 12, "predios": 254, "disponibles": 52},
  {"id": "jauja", "codigo": "PRY-016", "nombre": "Jauja", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 02", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=800&q=70&auto=format&fit=crop", "fase": "Levantamiento topografico", "estado": "En ejecucion", "presupuesto": "S/ 92.8 MM", "fisico": 29, "financiero": 64, "predios": 290, "disponibles": 117},
  {"id": "puerto-maldonado", "codigo": "PRY-017", "nombre": "Puerto Maldonado", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 03", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800&q=70&auto=format&fit=crop", "fase": "Saneamiento fisico legal", "estado": "En revision", "presupuesto": "S/ 12.4 MM", "fisico": 19, "financiero": 53, "predios": 200, "disponibles": 97},
  {"id": "tacna", "codigo": "PRY-018", "nombre": "Tacna", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 03", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1583500178690-f7eb3c2dd6cc?w=800&q=70&auto=format&fit=crop", "fase": "Liberacion predial", "estado": "En estructuracion", "presupuesto": "S/ 85.9 MM", "fisico": 73, "financiero": 42, "predios": 273, "disponibles": 27},
  {"id": "arequipa", "codigo": "PRY-019", "nombre": "Arequipa", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 03", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800&q=70&auto=format&fit=crop", "fase": "Disponibilidad de areas", "estado": "En ejecucion", "presupuesto": "S/ 102.1 MM", "fisico": 44, "financiero": 35, "predios": 73, "disponibles": 25},
  {"id": "caballococha", "codigo": "PRY-020", "nombre": "Caballococha", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 03", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=70&auto=format&fit=crop", "fase": "Diagnostico predial", "estado": "En revision", "presupuesto": "S/ 89.9 MM", "fisico": 49, "financiero": 46, "predios": 268, "disponibles": 82},
  {"id": "soplin-vargas", "codigo": "PRY-021", "nombre": "Soplin Vargas", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 03", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=800&q=70&auto=format&fit=crop", "fase": "Levantamiento topografico", "estado": "En estructuracion", "presupuesto": "S/ 88.3 MM", "fisico": 54, "financiero": 6, "predios": 276, "disponibles": 100},
  {"id": "huancabamba-oxapampa", "codigo": "PRY-022", "nombre": "Huancabamba - Oxapampa", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 03", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800&q=70&auto=format&fit=crop", "fase": "Saneamiento fisico legal", "estado": "En ejecucion", "presupuesto": "S/ 26.8 MM", "fisico": 24, "financiero": 36, "predios": 70, "disponibles": 65},
  {"id": "breu", "codigo": "PRY-023", "nombre": "Breu", "tipo": "Aeroportuarios", "coordinacionGeneral": "Coordinación General de Aeropuertos", "coordinacionPredial": "Coordinación Predial Aeropuertos 03", "coordinadorPredial": "Marcos Armando Soto Luis", "liderInterferencias": "Joel Jhonny Lázaro Anaya", "img": "https://images.unsplash.com/photo-1583500178690-f7eb3c2dd6cc?w=800&q=70&auto=format&fit=crop", "fase": "Liberacion predial", "estado": "En revision", "presupuesto": "S/ 94.0 MM", "fisico": 26, "financiero": 52, "predios": 166, "disponibles": 111},
  {"id": "autopista-del-sol", "codigo": "PRY-024", "nombre": "Autopista del Sol", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 1", "coordinacionPredial": "Coordinación Predial Autopista del Sol", "coordinadorPredial": "Marlon Napravnick Noriega", "liderInterferencias": "Jhony Elguera Rivas", "img": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=70&auto=format&fit=crop", "fase": "Disponibilidad de areas", "estado": "En estructuracion", "presupuesto": "S/ 51.8 MM", "fisico": 73, "financiero": 10, "predios": 125, "disponibles": 124},
  {"id": "red-vial-6", "codigo": "PRY-025", "nombre": "Red Vial 6", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 1", "coordinacionPredial": "Coordinación Predial Red Vial 6", "coordinadorPredial": "Raquel Antuanet Huapaya Porras", "liderInterferencias": "Marvin Antonio Mosquera Pérez", "img": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=70&auto=format&fit=crop", "fase": "Diagnostico predial", "estado": "En ejecucion", "presupuesto": "S/ 53.0 MM", "fisico": 45, "financiero": 61, "predios": 110, "disponibles": 219},
  {"id": "red-vial-5", "codigo": "PRY-026", "nombre": "Red Vial 5", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 1", "coordinacionPredial": "Coordinación Predial Red Vial 5", "coordinadorPredial": "Raquel Antuanet Huapaya Porras", "liderInterferencias": "María Cecilia Chil Chang", "img": "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?w=800&q=70&auto=format&fit=crop", "fase": "Levantamiento topografico", "estado": "En revision", "presupuesto": "S/ 56.2 MM", "fisico": 45, "financiero": 50, "predios": 252, "disponibles": 101},
  {"id": "dv-huaral-acos", "codigo": "PRY-027", "nombre": "Dv. Huaral - Acos", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 1", "coordinacionPredial": "Coordinación de Multiproyectos Viales 1", "coordinadorPredial": "Rafael Palomino Rojas", "liderInterferencias": "Marvin Antonio Mosquera Pérez", "img": "https://images.unsplash.com/photo-1473042904451-00171c69419d?w=800&q=70&auto=format&fit=crop", "fase": "Saneamiento fisico legal", "estado": "En estructuracion", "presupuesto": "S/ 84.5 MM", "fisico": 58, "financiero": 19, "predios": 117, "disponibles": 31},
  {"id": "dv-quilca-la-concordia", "codigo": "PRY-028", "nombre": "Dv. Quilca - La Concordia", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 1", "coordinacionPredial": "Coordinación de Multiproyectos Viales 1", "coordinadorPredial": "Rafael Palomino Rojas", "liderInterferencias": "Marvin Antonio Mosquera Pérez", "img": "https://images.unsplash.com/photo-1545262810-77515befe149?w=800&q=70&auto=format&fit=crop", "fase": "Liberacion predial", "estado": "En ejecucion", "presupuesto": "S/ 27.7 MM", "fisico": 39, "financiero": 47, "predios": 159, "disponibles": 13},
  {"id": "iirsa-sur-t1", "codigo": "PRY-029", "nombre": "IIRSA Sur T1", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 2", "coordinacionPredial": "Coordinación de Multiproyectos Viales 2", "coordinadorPredial": "Paul Alexander Orosco Jiménez", "liderInterferencias": "Cristina Modesta Pancorbo Sayas", "img": "https://images.unsplash.com/photo-1597171646371-aa961df17de1?w=800&q=70&auto=format&fit=crop", "fase": "Disponibilidad de areas", "estado": "En revision", "presupuesto": "S/ 62.3 MM", "fisico": 33, "financiero": 21, "predios": 184, "disponibles": 11},
  {"id": "iirsa-sur-t2", "codigo": "PRY-030", "nombre": "IIRSA Sur T2", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 2", "coordinacionPredial": "Coordinación de Multiproyectos Viales 2", "coordinadorPredial": "Paul Alexander Orosco Jiménez", "liderInterferencias": "Cristina Modesta Pancorbo Sayas", "img": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=70&auto=format&fit=crop", "fase": "Diagnostico predial", "estado": "En estructuracion", "presupuesto": "S/ 24.3 MM", "fisico": 57, "financiero": 44, "predios": 203, "disponibles": 42},
  {"id": "iirsa-sur-t3", "codigo": "PRY-031", "nombre": "IIRSA Sur T3", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 2", "coordinacionPredial": "Coordinación de Multiproyectos Viales 2", "coordinadorPredial": "Paul Alexander Orosco Jiménez", "liderInterferencias": "Cristina Modesta Pancorbo Sayas", "img": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=70&auto=format&fit=crop", "fase": "Levantamiento topografico", "estado": "En ejecucion", "presupuesto": "S/ 85.3 MM", "fisico": 75, "financiero": 65, "predios": 67, "disponibles": 126},
  {"id": "iirsa-sur-t4", "codigo": "PRY-032", "nombre": "IIRSA Sur T4", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 2", "coordinacionPredial": "Coordinación de Multiproyectos Viales 2", "coordinadorPredial": "Paul Alexander Orosco Jiménez", "liderInterferencias": "Cristina Modesta Pancorbo Sayas", "img": "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?w=800&q=70&auto=format&fit=crop", "fase": "Saneamiento fisico legal", "estado": "En revision", "presupuesto": "S/ 108.7 MM", "fisico": 60, "financiero": 30, "predios": 244, "disponibles": 110},
  {"id": "iirsa-sur-t5", "codigo": "PRY-033", "nombre": "IIRSA Sur T5", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 2", "coordinacionPredial": "Coordinación de Multiproyectos Viales 2", "coordinadorPredial": "Paul Alexander Orosco Jiménez", "liderInterferencias": "Cristina Modesta Pancorbo Sayas", "img": "https://images.unsplash.com/photo-1473042904451-00171c69419d?w=800&q=70&auto=format&fit=crop", "fase": "Liberacion predial", "estado": "En estructuracion", "presupuesto": "S/ 19.6 MM", "fisico": 61, "financiero": 8, "predios": 137, "disponibles": 27},
  {"id": "carretera-puno-juliaca", "codigo": "PRY-034", "nombre": "Carretera Puno Juliaca", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 2", "coordinacionPredial": "Coordinación de Multiproyectos Viales 2", "coordinadorPredial": "Paul Alexander Orosco Jiménez", "liderInterferencias": "Cristina Modesta Pancorbo Sayas", "img": "https://images.unsplash.com/photo-1545262810-77515befe149?w=800&q=70&auto=format&fit=crop", "fase": "Disponibilidad de areas", "estado": "En ejecucion", "presupuesto": "S/ 118.3 MM", "fisico": 66, "financiero": 15, "predios": 96, "disponibles": 97},
  {"id": "iirsa-centro", "codigo": "PRY-035", "nombre": "IIRSA Centro", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 2", "coordinacionPredial": "Coordinación de Multiproyectos Viales 2", "coordinadorPredial": "Paul Alexander Orosco Jiménez", "liderInterferencias": "Cristina Modesta Pancorbo Sayas", "img": "https://images.unsplash.com/photo-1597171646371-aa961df17de1?w=800&q=70&auto=format&fit=crop", "fase": "Diagnostico predial", "estado": "En revision", "presupuesto": "S/ 75.3 MM", "fisico": 23, "financiero": 5, "predios": 117, "disponibles": 147},
  {"id": "iirsa-norte", "codigo": "PRY-036", "nombre": "IIRSA Norte", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 2", "coordinacionPredial": "Coordinación de Multiproyectos Viales 2", "coordinadorPredial": "Paul Alexander Orosco Jiménez", "liderInterferencias": "Cristina Modesta Pancorbo Sayas", "img": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=70&auto=format&fit=crop", "fase": "Levantamiento topografico", "estado": "En estructuracion", "presupuesto": "S/ 19.4 MM", "fisico": 56, "financiero": 44, "predios": 53, "disponibles": 28},
  {"id": "longitudinal-de-la-sierra-t2", "codigo": "PRY-037", "nombre": "Longitudinal de la Sierra T2", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 3", "coordinacionPredial": "Coordinación Predial Longitudinal de la Sierra Tramo 2", "coordinadorPredial": "Freddy Justo Rojas Meza", "liderInterferencias": "Por designar", "img": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=70&auto=format&fit=crop", "fase": "Saneamiento fisico legal", "estado": "En ejecucion", "presupuesto": "S/ 105.9 MM", "fisico": 58, "financiero": 14, "predios": 169, "disponibles": 98},
  {"id": "longitudinal-de-la-sierra-t4", "codigo": "PRY-038", "nombre": "Longitudinal de la Sierra T4", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 3", "coordinacionPredial": "Coordinación Predial Longitudinal de la Sierra Tramo 4", "coordinadorPredial": "Nelson Efraín Gutiérrez Minchola", "liderInterferencias": "Por designar", "img": "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?w=800&q=70&auto=format&fit=crop", "fase": "Liberacion predial", "estado": "En revision", "presupuesto": "S/ 75.5 MM", "fisico": 70, "financiero": 12, "predios": 99, "disponibles": 227},
  {"id": "dv-nuevo-mocupe-cayalti", "codigo": "PRY-039", "nombre": "Dv. Nuevo Mocupe - Cayalti", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 3", "coordinacionPredial": "Coordinación de Multiproyectos Viales 3", "coordinadorPredial": "Nelson Efraín Gutiérrez Minchola", "liderInterferencias": "Por designar", "img": "https://images.unsplash.com/photo-1473042904451-00171c69419d?w=800&q=70&auto=format&fit=crop", "fase": "Disponibilidad de areas", "estado": "En estructuracion", "presupuesto": "S/ 62.7 MM", "fisico": 69, "financiero": 35, "predios": 287, "disponibles": 89},
  {"id": "dv-buenos-aires-canchaque", "codigo": "PRY-040", "nombre": "Dv. Buenos Aires - Canchaque", "tipo": "Viales", "coordinacionGeneral": "Coordinación General Vial 3", "coordinacionPredial": "Coordinación de Multiproyectos Viales 3", "coordinadorPredial": "Nelson Efraín Gutiérrez Minchola", "liderInterferencias": "Por designar", "img": "https://images.unsplash.com/photo-1545262810-77515befe149?w=800&q=70&auto=format&fit=crop", "fase": "Diagnostico predial", "estado": "En ejecucion", "presupuesto": "S/ 17.6 MM", "fisico": 23, "financiero": 52, "predios": 215, "disponibles": 199},
  {"id": "red-vial-4", "codigo": "PRY-041", "nombre": "Red Vial 4", "tipo": "Viales", "coordinacionGeneral": "Coordinación General de Proyectos Viales y Especiales", "coordinacionPredial": "Coordinación Predial Red Vial 4", "coordinadorPredial": "Wenne Esteisy Jesús Loza", "liderInterferencias": "Ángel Enrique Reyes Cruz", "img": "https://images.unsplash.com/photo-1597171646371-aa961df17de1?w=800&q=70&auto=format&fit=crop", "fase": "Levantamiento topografico", "estado": "En revision", "presupuesto": "S/ 37.7 MM", "fisico": 30, "financiero": 38, "predios": 51, "disponibles": 62},
  {"id": "puerto-san-juan-de-marcona", "codigo": "PRY-042", "nombre": "Puerto San Juan de Marcona", "tipo": "Especiales", "coordinacionGeneral": "Coordinación General de Proyectos Viales y Especiales", "coordinacionPredial": "Coordinación de Multiproyectos Especiales", "coordinadorPredial": "José César Mendoza Soto", "liderInterferencias": "Ángel Enrique Reyes Cruz", "img": "https://images.unsplash.com/photo-1473221326025-9183b464bb7e?w=800&q=70&auto=format&fit=crop", "fase": "Saneamiento fisico legal", "estado": "En estructuracion", "presupuesto": "S/ 114.5 MM", "fisico": 56, "financiero": 14, "predios": 53, "disponibles": 204},
  {"id": "evitamiento-cuzco", "codigo": "PRY-043", "nombre": "Evitamiento Cuzco", "tipo": "Especiales", "coordinacionGeneral": "Coordinación General de Proyectos Viales y Especiales", "coordinacionPredial": "Coordinación de Multiproyectos Especiales", "coordinadorPredial": "José César Mendoza Soto", "liderInterferencias": "Ángel Enrique Reyes Cruz", "img": "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=70&auto=format&fit=crop", "fase": "Liberacion predial", "estado": "En ejecucion", "presupuesto": "S/ 67.1 MM", "fisico": 21, "financiero": 49, "predios": 173, "disponibles": 142},
  {"id": "anillo-vial-periferico", "codigo": "PRY-044", "nombre": "Anillo Vial Periférico", "tipo": "Especiales", "coordinacionGeneral": "Coordinación General de Proyectos Viales y Especiales", "coordinacionPredial": "Coordinación de Multiproyectos Especiales", "coordinadorPredial": "José César Mendoza Soto", "liderInterferencias": "Ángel Enrique Reyes Cruz", "img": "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=70&auto=format&fit=crop", "fase": "Disponibilidad de areas", "estado": "En revision", "presupuesto": "S/ 49.1 MM", "fisico": 31, "financiero": 27, "predios": 154, "disponibles": 146},
  {"id": "fhh", "codigo": "PRY-045", "nombre": "FHH", "tipo": "Especiales", "coordinacionGeneral": "Coordinación General de Proyectos Viales y Especiales", "coordinacionPredial": "Coordinación de Multiproyectos Especiales", "coordinadorPredial": "José César Mendoza Soto", "liderInterferencias": "Ángel Enrique Reyes Cruz", "img": "https://images.unsplash.com/photo-1473221326025-9183b464bb7e?w=800&q=70&auto=format&fit=crop", "fase": "Diagnostico predial", "estado": "En estructuracion", "presupuesto": "S/ 68.7 MM", "fisico": 74, "financiero": 26, "predios": 154, "disponibles": 166},
  {"id": "puertos-y-otros", "codigo": "PRY-046", "nombre": "Puertos y otros", "tipo": "Especiales", "coordinacionGeneral": "Coordinación General de Proyectos Viales y Especiales", "coordinacionPredial": "Coordinación de Multiproyectos Especiales", "coordinadorPredial": "José César Mendoza Soto", "liderInterferencias": "Ángel Enrique Reyes Cruz", "img": "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=70&auto=format&fit=crop", "fase": "Levantamiento topografico", "estado": "En ejecucion", "presupuesto": "S/ 98.9 MM", "fisico": 34, "financiero": 56, "predios": 162, "disponibles": 219},
  {"id": "otros-proyectos-especiales", "codigo": "PRY-047", "nombre": "Otros proyectos especiales", "tipo": "Especiales", "coordinacionGeneral": "Coordinación General de Proyectos Viales y Especiales", "coordinacionPredial": "Coordinación de Multiproyectos Especiales", "coordinadorPredial": "José César Mendoza Soto", "liderInterferencias": "Ángel Enrique Reyes Cruz", "img": "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=70&auto=format&fit=crop", "fase": "Saneamiento fisico legal", "estado": "En revision", "presupuesto": "S/ 52.9 MM", "fisico": 39, "financiero": 17, "predios": 292, "disponibles": 101},
];

const airportImages = Object.fromEntries(
  [
    "iquitos",
    "trujillo",
    "chachapoyas",
    "chiclayo",
    "tumbes",
    "pucallpa",
    "anta-huaraz",
    "pisco",
    "tarapoto",
    "cajamarca",
    "talara",
    "piura",
    "andahuaylas",
    "ayacucho",
    "juliaca",
    "jauja",
    "puerto-maldonado",
    "tacna",
    "arequipa",
    "caballococha",
    "soplin-vargas",
    "huancabamba-oxapampa",
    "breu",
  ].map((id) => [id, `${import.meta.env.BASE_URL}images/airports/${id}.jpg`]),
) as Record<string, string>;

export const proyectos: Proyecto[] = projectSeed.map((project) => ({
  ...project,
  img: airportImages[project.id] ?? project.img,
}));

export function getProyecto(id: string): Proyecto | undefined {
  return proyectos.find((p) => p.id === id);
}
