"""add_book_types_library_visibility

Revision ID: 51532e331a2f
Revises: c3f1d8a92e10
Create Date: 2026-03-28 13:15:15.964291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51532e331a2f'
down_revision: Union[str, Sequence[str], None] = 'c3f1d8a92e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('book_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_types_id'), ['id'], unique=False)

    op.create_table('library_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'library_id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_books_book_type_id', 'book_types', ['book_type_id'], ['id'])

    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('saved_filters', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_filters', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.drop_column('is_public')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_book_type_id', type_='foreignkey')
        batch_op.drop_column('book_type_id')

    op.drop_table('library_users')
    with op.batch_alter_table('book_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_types_id'))

    op.drop_table('book_types')
    # ### end Alembic commands ###
