"""add_books_and_book_files

Revision ID: b87f11474be0
Revises: 7d4ea46f5c85
Create Date: 2026-03-27 15:39:18.093194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87f11474be0'
down_revision: Union[str, Sequence[str], None] = '7d4ea46f5c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('series', sa.Text(), nullable=True),
    sa.Column('series_index', sa.Float(), nullable=True),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('cover_path', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_id'), ['id'], unique=False)

    op.create_table('book_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('book_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_files_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_files_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_files_id'))
        batch_op.drop_index(batch_op.f('ix_book_files_content_hash'))

    op.drop_table('book_files')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_id'))
        batch_op.drop_index(batch_op.f('ix_books_content_hash'))

    op.drop_table('books')
    # ### end Alembic commands ###
