#!/usr/bin/env bash
#
# Tome easy installer - gets Tome running via Docker with zero Docker knowledge.
#
#   curl -fsSL https://tome.bndct.sh/install.sh | bash
#
# What it does:
#   1. Checks Docker is installed and running (with friendly help if not).
#   2. Creates ~/Tome with a compose file and data/books/bindery folders.
#   3. Picks a free port, pulls the image, starts Tome.
#   4. Waits until Tome actually answers, then prints the address to open
#      (including the LAN address your Kindle/phone use).
#
# Re-running it is safe: it updates the existing install in place, keeps the
# same port, and never touches your library or data.
#
# Env overrides:
#   TOME_DIR=<path>         where to install        (default: ~/Tome)
#   TOME_PORT=<n>           force a specific web port
#   TOME_INSTALL_DRYRUN=1   set up files but don't touch Docker (for testing)

set -euo pipefail

IMAGE="ghcr.io/bndct-devops/tome:latest"
INSTALL_DIR="${TOME_DIR:-$HOME/Tome}"
DRYRUN="${TOME_INSTALL_DRYRUN:-0}"

bold() { printf "\033[1m%s\033[0m\n" "$1"; }
info() { printf "   %s\n" "$1"; }
warn() { printf "\033[33m   %s\033[0m\n" "$1"; }
err()  { printf "\033[31m!! %s\033[0m\n" "$1" >&2; }

# Is something already listening on 127.0.0.1:$1 ? Pure bash, no extra tools.
port_in_use() { (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1; }

# First free port at or above $1 (gives up after 50 tries).
find_free_port() {
  local p="$1" tries=0
  while port_in_use "$p"; do
    p=$((p + 1)); tries=$((tries + 1))
    if [ "$tries" -gt 50 ]; then
      err "Couldn't find a free port near $1. Set TOME_PORT to one you know is free."
      exit 1
    fi
  done
  printf '%s' "$p"
}

echo
bold "Tome installer"
echo

# --- 1. Docker installed? ---------------------------------------------------
if [ "$DRYRUN" != "1" ] && ! command -v docker >/dev/null 2>&1; then
  err "Docker isn't installed yet."
  echo
  info "Tome runs inside Docker (a free app that keeps it self-contained)."
  info "Install Docker Desktop, then run this installer again:"
  case "$(uname -s)" in
    Darwin) info "  Mac:     https://www.docker.com/products/docker-desktop/";;
    Linux)  info "  Linux:   https://docs.docker.com/engine/install/";;
    *)      info "  Windows: https://www.docker.com/products/docker-desktop/";;
  esac
  echo
  exit 1
fi

# --- 2. Compose available? + 3. daemon running? ----------------------------
COMPOSE=""
if [ "$DRYRUN" != "1" ]; then
  if docker compose version >/dev/null 2>&1; then
    COMPOSE="docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE="docker-compose"
  else
    err "Docker is installed but Docker Compose isn't available."
    info "Update Docker Desktop (it bundles Compose) and run this again."
    exit 1
  fi

  if ! docker info >/dev/null 2>&1; then
    err "Docker is installed but not running."
    info "Start Docker Desktop (the whale icon in your menu bar / system tray),"
    info "wait until it says 'running', then run this installer again."
    exit 1
  fi
fi

# --- 4. Decide which port to use -------------------------------------------
COMPOSE_FILE="$INSTALL_DIR/docker-compose.yml"
PORT=""
if [ -n "${TOME_PORT:-}" ]; then
  PORT="$TOME_PORT"                       # user forced one - respect it
elif [ -f "$COMPOSE_FILE" ]; then
  # Existing install: reuse its port so updates stay on the same address
  # (and we don't accidentally spin up a second copy on a different port).
  PORT=$(grep -oE '[0-9]+:8080' "$COMPOSE_FILE" 2>/dev/null | head -1 | cut -d: -f1)
fi
PORT="${PORT:-8080}"

# Fresh install only: if the wanted port is taken by something else, move up.
if [ ! -f "$COMPOSE_FILE" ] && [ -z "${TOME_PORT:-}" ] && port_in_use "$PORT"; then
  NEWPORT=$(find_free_port "$((PORT + 1))")
  warn "Port $PORT is already in use; using $NEWPORT instead."
  PORT="$NEWPORT"
fi

# --- 5. Write folder + compose file ----------------------------------------
bold "Setting up Tome in: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR/data" "$INSTALL_DIR/books" "$INSTALL_DIR/bindery"

cat > "$COMPOSE_FILE" <<YML
# Generated by the Tome installer. Edit paths/port here if you like.
services:
  tome:
    image: $IMAGE
    container_name: tome
    ports:
      - "$PORT:8080"
    volumes:
      - ./data:/data       # database, covers, generated secret key
      - ./books:/books     # your ebook library (Tome organises files here)
      - ./bindery:/bindery # drop new files here for review/import
    restart: unless-stopped
YML
info "Wrote docker-compose.yml (port $PORT)"

# --- 6. Pull + start --------------------------------------------------------
if [ "$DRYRUN" = "1" ]; then
  info "(dry run - skipping docker pull/up)"
else
  echo
  bold "Downloading and starting Tome (first run can take a minute)..."
  if ! ( cd "$INSTALL_DIR" && $COMPOSE pull && $COMPOSE up -d ); then
    echo
    err "Docker couldn't start Tome."
    info "See what went wrong:  cd \"$INSTALL_DIR\" && $COMPOSE logs"
    info "A common cause is a leftover container named 'tome':"
    info "  docker rm -f tome   # then run this installer again"
    exit 1
  fi

  # --- 7. Wait until Tome actually answers ---------------------------------
  if command -v curl >/dev/null 2>&1; then
    printf "   Waiting for Tome to come up"
    up=0; n=0
    while [ "$n" -lt 30 ]; do
      if curl -fsS "http://127.0.0.1:$PORT/api/health" >/dev/null 2>&1; then up=1; break; fi
      printf "."; sleep 1; n=$((n + 1))
    done
    printf "\n"
    if [ "$up" != "1" ]; then
      warn "Tome started but isn't responding yet - it may just be slow."
      info "If the page below doesn't load, check:  cd \"$INSTALL_DIR\" && $COMPOSE logs"
    fi
  fi
fi

# --- 8. Where to reach it ---------------------------------------------------
lan_ip=""
case "$(uname -s)" in
  Darwin) lan_ip=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true);;
  Linux)  lan_ip=$(hostname -I 2>/dev/null | awk '{print $1}' || true);;
esac

echo
bold "Done - Tome is running."
info "On this computer:          http://localhost:$PORT"
if [ -n "$lan_ip" ]; then
  info "From your Kindle / phone:  http://$lan_ip:$PORT   (use this in the KOReader plugin)"
fi
info "Your books go in:          $INSTALL_DIR/books"
echo
info "Stop Tome:    cd \"$INSTALL_DIR\" && ${COMPOSE:-docker compose} down"
info "Update Tome:  re-run this installer (it keeps your data and port)"
echo
